test_dataset:
  dataset:
    name: darcy-flow-pt
    args:
      path: ./data/darcy_test_64.pt
      field: y
      first_k: 1000
  wrapper:
    name: pde-implicit-downsampled
    args:
      scale_min: 2
      scale_max: 2
      augment: false
      interpolation: bicubic
  batch_size: 1
  num_workers: 0

eval_type: pde-rel-l2
clamp_output: false

data_norm:
  inp: {sub: [0.0], div: [1.0]}
  gt: {sub: [0.0], div: [1.0]}
